### ISSUE TITLE
Incompatible with node 7

### ISSUE THREAD

**Issue by alhaag** [noahsug/json5-writer#1]
Congratulations first, this library is very useful.

I just wish it was compatible with NodeJS version 7 as I need to use it in kernel 2.6 which doesn't support larger versions of NodeJS.
I verified that the spread operator is supported from version 8 onwards.

To be compatible simply replace "... options" with "Object.assign" the two occurrences present in the src / index.js file.

If you prefer I can make a pull request.

Thanks in advance.

**Comment by alhaag** [comment]
Made pull request https://github.com/noahsug/json5-writer/pull/2

**Comment by noahsug** [comment]
Thank you! Merged. `json5-writer@0.1.8` should be compatible with NodeJS v7

**Comment by alhaag** [comment]
I thank you.
I'm closing the issue
